### ISSUE TITLE
Various questions

### ISSUE THREAD

**Issue by alehander92** [tree-sitter/tree-sitter-ruby#105]
Hey

I am sorry but i couldnt find an irc or something

I am trying to change the grammar output for personal needs a bit and i am wondering about some things: 
is it possible to somehow generate a named node for optional even if it doesnt match? i tried choice between optional and nil_node where nil_node accepts empty string but this doesnt seem nice

overally is there a way to add a named "nil_node" in some places always? it should just be generated , equivalently to always matching an empty string, but i am not sure how to do it as it seems to break other stuff

**Comment by maxbrunsfeld** [comment]
No, Tree-sitter does not support grammar rules that match the empty string. Instead, you should make the rule itself optional.
