### ISSUE TITLE
Cut new release with new ABI 69

### ISSUE THREAD

**Issue by maletor** [tree-sitter/tree-sitter-ruby#107]
My version of Node has

```
> process.platform
'linux'
> process.arch
'x64'
> process.versions.modules
'67'
> process.version
'v11.15.0'
```

can you recompile and release for 67 (and preemptively for 69)?

**Comment by Arcanemagus** [comment]
Although adding those versions to the [`prebuild` configuration](https://github.com/tree-sitter/tree-sitter-ruby/blob/f98f435b188a887355771f212da40cecaa5866ae/package.json#L23) is a good idea, your system _should_ be detecting that there isn't a prebuilt version existing and compiling it locally. Is that not working?

**Comment by maletor** [comment]
@Arcanemagus, yes, you are not wrong.

However, as additional context, it should resolve this bug: https://github.com/rubyide/vscode-ruby/issues/486

(Happened before and I believe the maintainer is wanting to switch to WASM to avoid in the future.)

**Comment by maletor** [comment]
Moving to https://github.com/tree-sitter/tree-sitter-ruby/pull/108

**Comment by wingrunr21** [comment]
Just for color here @Arcanemagus:

This is used in an electron extension in VSCode. The way VSCode handles extensions + the fact it is being consumed via an extension and not in a traditional NPM workflow makes building a new binary on demand more problematic (like lack of build tooling being available).

My long term solve will be to switch over to using the WASM build of `tree-sitter` but that wasn't available when I first did the implementation.
