### ISSUE TITLE
Final `end` does not get highlighted after a block with a rescue inside a method

### ISSUE THREAD

**Issue by calebmeyer** [tree-sitter/tree-sitter-ruby#112]
### Description
Ruby 2.6 added the ability to do a rescue without a corresponding begin inside a block. That means code like
```ruby
arr.each do |thing|
  begin
    try(thing)
  rescue error
    handle_it
  end
end
```
can be rewritten a little shorter (omitting the begin, and fixing the indentation):
```ruby
arr.each do |thing|
  try(thing)
rescue error
  handle_it
end
```

### Steps to Reproduce

1. Put a block like the above into a method

**Expected behavior:**
All `end` tags are syntax highlighted

**Actual behavior:**
The method's end tag loses highlighting:
![image](https://user-images.githubusercontent.com/3342777/63360444-04566f80-c334-11e9-84f7-8ef183150cca.png)

**Reproduces how often:**
100% of the time

### Versions
```
atom --version

Atom    : 1.40.0
Electron: 3.1.10
Chrome  : 66.0.3359.181
Node    : 10.2.0

apm --version
apm  2.4.2
npm  6.2.0
node 10.2.1 x64
atom 1.40.0
python 3.7.2
git 2.16.2.windows.1
visual studio

OS: Windows 10 Enterprise (1809)
```

### Additional Information
I originally logged this as https://github.com/atom/language-ruby/issues/274

**Comment by patrickt** [comment]
Hmm. Definitely doesn’t look like Atom is doing the right thing here. The tree _seems_ plausible:
```
(program [0, 0] - [5, 0]
  (method_call [0, 0] - [4, 3]
    method: (call [0, 0] - [0, 8]
      receiver: (identifier [0, 0] - [0, 3])
      method: (identifier [0, 4] - [0, 8]))
    block: (do_block [0, 9] - [4, 3]
      (block_parameters [0, 12] - [0, 19]
        (identifier [0, 13] - [0, 18]))
      (method_call [1, 2] - [1, 12]
        method: (identifier [1, 2] - [1, 5])
        arguments: (argument_list [1, 5] - [1, 12]
          (identifier [1, 6] - [1, 11])))
      (rescue [2, 0] - [3, 11]
        exceptions: (exceptions [2, 7] - [2, 12]
          (identifier [2, 7] - [2, 12]))
        body: (then [2, 12] - [3, 11]
          (identifier [3, 2] - [3, 11]))))))
```

**Comment by patrickt** [comment]
Might it be that Atom is using an outdated grammar?

**Comment by maxbrunsfeld** [comment]
Yeah, I recently fixed this in https://github.com/tree-sitter/tree-sitter-ruby/commit/575d74b2de64476b57c8ec87d2e01ce19c82df68. We need to upgrade tree-sitter-ruby in Atom.

**Comment by patrickt** [comment]
Looks like we should close this and reopen https://github.com/atom/language-ruby/issues/274 (or a similar issue re. bumping tree-sitter-ruby).
