### ISSUE TITLE
Parse error on 'not pattern match' operator

### ISSUE THREAD

**Issue by mschwager** [tree-sitter/tree-sitter-ruby#143]
The file in question comes from `brew`: [`regexp_match.rb`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.9.1/lib/rubocop/cop/performance/regexp_match.rb).

The following is a reduced example:

```ruby
def correct_operator(corrector, recv, arg, oper = nil)
  op_range = correction_range(recv, arg)

  replace_with_match_predicate_method(corrector, recv, arg, op_range)

  corrector.insert_after(arg.loc.expression, ')') unless op_range.source.end_with?('(')
  corrector.insert_before(recv.loc.expression, '!') if oper == :!~
end
```

It appears that the parse error is coming from `:!~`, which is the ['not pattern match' operator](https://www.tutorialspoint.com/ruby/ruby_operators.htm) (`!~`).

```
$ tree-sitter parse not-pattern-match.rb 
(ERROR [0, 0] - [8, 0]
...
not-pattern-match.rb	1 ms	(ERROR [0, 0] - [8, 0])
```

```
$ ruby -c not-pattern-match.rb 
Syntax OK
```

**Comment by nbrahms** [comment]
This appears to be a parse error on the symbol, rather than the operator.

Presumably this file from the Ruby spec test suite should parse: https://github.com/ruby/spec/blob/master/language/symbol_spec.rb

**Comment by maxbrunsfeld** [comment]
Thanks for the report!
