### ISSUE TITLE
Parse error on loop iterator

### ISSUE THREAD

**Issue by mschwager** [tree-sitter/tree-sitter-ruby#146]
The file in question comes from `metasploit-framework`: [`enum_ie.rb`](https://github.com/rapid7/metasploit-framework/blob/master/modules/post/windows/gather/enum_ie.rb).

Minimized example:

```ruby
def is_86
  pid = session.sys.process.open.pid
  return session.sys.process.each_process.find { |i| i["pid"] == pid} ["arch"] == "x86"
end
```

It appears to be failing on the `{ |i| i["pid"] == pid}` portion.

```
$ tree-sitter parse loop-iter.rb 
...
loop-iter.rb	0 ms	(ERROR [2, 47] - [2, 69])
```

```
$ ruby -c loop-iter.rb 
Syntax OK
```

**Comment by maxbrunsfeld** [comment]
Reduced example:

```rb
a { |b| c } ["d"] = "e"
```
