### ISSUE TITLE
Symbols are highlighted the same as Constants

### ISSUE THREAD

**Issue by semanticart** [tree-sitter/tree-sitter-ruby#158]
Thanks for this excellent project! 

I'm using `nvim-treesitter` and 8fd340fe8b47b53e7dada53c3913661949c34f6b and seeing Symbols highlighted the same as Constants. Is there a way to distinguish between the two so I can highlight them differently?

Here's screenshots using `:TSHighlightCapturesUnderCursor` from `nvim-treesitter/playground`

![Screen Shot 2021-01-25 at 11 41 30 AM](https://user-images.githubusercontent.com/8633/105736809-3560a980-5f03-11eb-8f88-5d25af254ef9.jpg)

![Screen Shot 2021-01-25 at 11 41 21 AM](https://user-images.githubusercontent.com/8633/105736827-3b568a80-5f03-11eb-9435-b13a2f5a158b.jpg)

**Comment by patrickt** [comment]
Hey there! This would be better served as an issue on https://github.com/nvim-treesitter/nvim-treesitter, as tree-sitter doesn’t have any control over how symbols are highlighted in a UI. The queries that back those do differentiate between symbols and constants, so how that information is used is up to the invoking plugin.
