### ISSUE TITLE
Tests/CI fail with CRLF line endings

### ISSUE THREAD

**Issue by lukedan** [tree-sitter/tree-sitter-ruby#164]
The following tests fail for CRLF line endings:
- `corpus - declarations - unparenthesized call as superclass`
- `corpus - expressions - method call with line break`
- `corpus - expressions - backslash-newline as line continuation`
- `corpus - literals - newline-delimited strings`
- `ruby_errors - Heredocs with errors`

See also tree-sitter/tree-sitter#913

**Comment by maxbrunsfeld** [comment]
Thanks for the report!

**Comment by patrickt** [comment]
This is causing the Windows builds on https://github.com/tree-sitter/tree-sitter-ruby/pull/166 to fail; once we fix that, we should reenable them.
