### ISSUE TITLE
Folding not working in Tresitter

### ISSUE THREAD

**Issue by sphynx79** [tree-sitter/tree-sitter-ruby#165]
Hi thanks for your support. 
I saw that folding not working for Neovim with Tresitter, and I realized that theris'nt in query folder for ruby the file folds.scm.
Can you create this query or tell me how i can create this file for Treesitter work right in my Neovim with ruby

Thanks

**Comment by patrickt** [comment]
Hi there. If you’re having trouble with Neovim’s tree-sitter integration, issues are best left on their repository (https://github.com/nvim-treesitter/nvim-treesitter). Neither tree-sitter nor its parsers are responsible for the details of code folding, as that behavior varies across editors.
