### ISSUE TITLE
Fail to parse def foo(...)

### ISSUE THREAD

**Issue by aryx** [tree-sitter/tree-sitter-ruby#167]
This does not currently parse correctly:
```
 def perform_later(...)
        job = job_or_instantiate(...)
        enqueue_result = job.enqueue
        foo()
end
```
It's because it's using a recent Ruby extension about arguments forwarding with '...'.

**Comment by aibaars** [comment]
Should be fixed by https://github.com/tree-sitter/tree-sitter-ruby/pull/191
