### ISSUE TITLE
incorrect representation of range expression in the presence of negative integer arguments

### ISSUE THREAD

**Issue by julianthome** [tree-sitter/tree-sitter-ruby#171]
The current grammar fails to parse ranges correctly if they contain negative numbers:

```
(1..5).to_a        #=> [1, 2, 3, 4, 5] -> OK
('a'..'e').to_a    #=> ["a", "b", "c", "d", "e"] -> OK
('a'...'e').to_a   #=> ["a", "b", "c", "d"] = -5..-1 -> OK
(-1..-5).to_a      #=> [], -> FAILS
(-5..-1).to_a      #=> [-5, -4, -3, -2, -1] -> FAILS
```
The figure below depicts the corresponding tree-sitter tree:

![image](https://user-images.githubusercontent.com/5645429/116036486-13440800-a667-11eb-9c4b-5e3587b01b2a.png)

For the cases, where a range was recognized correctly, it is rooted with a `range` node. The incorrect cases are rooted with a `binary` node and the `range` node only has a single `unary` child.

For all cases, I would suggest to use a different labeling for the `parenthesized_statements` because `range` is an expression.

**Comment by aibaars** [comment]
This should be fixed by https://github.com/tree-sitter/tree-sitter-ruby/pull/207.
