### ISSUE TITLE
Parses method calls indirectly as local variables

### ISSUE THREAD

**Issue by skanev** [tree-sitter/tree-sitter-ruby#173]
Hey.

I think treesitter gets a fundamental Ruby syntax element wrong. Here's a (simplified) example from the corpus:

```
===============================
method call
===============================

foo
foo()

---

(program
  (identifier)
  (call
    method: (identifier)
    arguments: (argument_list)))
```

The first line is incorrectly parsed as `(identifier)`, while it should be identical to the second line.

Ruby has optional parentheses, but it needs to disambiguate between method calls and variables. To do so, it treats an unqualified identifier as a method call, unless there is an assignment locally to the same name, which then makes it a variable. Here's an example with the [parser](https://github.com/whitequark/parser) gem (which is not the reference parser, but it is consistent with it):

```ruby
require 'parser/current'

def parse(code)
  p Parser::CurrentRuby.parse(code)
end

parse <<END
foo
END

parse <<END
foo = 1
foo
END
```

It produces the following ASTs:

```
s(:send, nil, :foo)

s(:begin,
  s(:lvasgn, :foo,
    s(:int, 1)),
  s(:lvar, :foo))
```

Note that it knows the first one is a method call.  Also note that here

```ruby
foo
```

...and here...

```ruby
foo = 1
foo
```

...the GitHub syntax highlighting gets it right.

As a more contrived example, note that the following ruby code:

```ruby
foo
foo = 1
foo
```

parses with the following AST:

```
s(:begin,
  s(:send, nil, :foo),
  s(:lvasgn, :foo,
    s(:int, 1)),
  s(:lvar, :foo))

```

The first line is a method call, while the third one is a variable reference.

Two bits of ruby trivia, that support this:

```ruby
def try_it
  #x = 0
  eval 'x = 1'
  puts x
end
```

The program above errors out with "undefined local variable or method `x`", despite of the `eval` happening, because the parser has already determined this is a method call, and it can't find it. If I uncomment the commented out line, however, the program outputs 1, as expected.

Second, the following program:

```ruby
def foo
  'method'
end

def try_it
  puts foo.inspect
  foo = 'value' if false
  puts foo.inspect
end

try_it
```

will output `"method"` and then `nil`, because at the point of the last invocation it has determined it's a local variable, even if the conditional's body didn't get executed, and it initialized it with `nil`. Additionally, note that this is again evident in GitHub's highlighting.

Why does this matter? The syntax highlighting from tree-sitter is wrong. There are enough places in pretty much all code that are method calls, but get colored as variables, even if (1) they aren't and (2) it's determinable parse-time.

Going through the corpus, I can see it's wrong in a lot of places. I think it needs to be updated, and the parser fixed. I'd love to help, but my parser-fu is weak. If the maintainers agree with this issue and intend to fix it, I'm more than happy to volunteer to update the corpus in a branch and somebody else can then tweak the parser. Alternatively, and even better for me, I'm game if somebody updates the parser and introduces a few examples in the corpus, and then I can manually go, fix and verify everything else. Let me know if there are any takers :)

Hope this is useful.

**Comment by aryx** [comment]
This is a context-sensitive disambiguation which requires more than just parsing but requires also to resolve names.
I don't think tree-sitter can do that at parsing time.

**Comment by skanev** [comment]
I agree it's context-sensitive in the "context-free" vs "context-sensitive" vs "regular" terminology, but I'm unsure what you mean by "resolve names". This is completely limited to local scopes, and scopes get created by `def`, `class` and `module`, and don't get inherited. As in, in the following code:

```ruby
foo = 1

def something
  foo
end
```

The second `foo` is a method call for sure.

As in, we need to know that there has been an assignment prior to the variable reference, but not anything more than that (e.g. what it has been assigned to). Simply, it needs to maintain a symbol table within the `def`, `module` or `class` expressions.

I don't know enough treesitter, sadly, but I'll read up a bit on it. There's bound to be another language that also needs symbol tables in order to emit ASTs (I remember C++ had a context-sensitive element, but I don't remember what exactly).
