### ISSUE TITLE
heredoc_body should not be declared as an extra

### ISSUE THREAD

**Issue by mjambon** [tree-sitter/tree-sitter-ruby#176]
I'm not sure why `heredoc_body` is [declared as an extra](https://github.com/tree-sitter/tree-sitter-ruby/blob/391269d74d20154bbd0ac9be20b35eced6920290/grammar.js#L71) i.e. a node that can occur anywhere, like a comment.

If it occurred in a grammar rule, such as after `heredoc_beginning`, then could have it in the [typed CST we generate with ocaml-tree-sitter](https://github.com/returntocorp/semgrep-ruby/blob/main/lib/CST.ml).

**Comment by maxbrunsfeld** [comment]
The rule for heredoc bodies is that they start on the next line after a heredoc start, no matter what is going on syntactically. I don't really think there's a good way to model them in the grammar besides including them as an extra.

**Comment by mjambon** [comment]
oh. Great examples. That makes a ton of sense.

I guess a solution for ocaml-tree-sitter is to make a first pass on the tree to pair the `heredoc_beginning` with the next `heredoc_body`, or something like this.
