### ISSUE TITLE
Multiline assignments not indenting

### ISSUE THREAD

**Issue by brandoncc** [tree-sitter/tree-sitter-ruby#178]
Thanks for all of the hard work on this!

I am finding that multi-line assignments do not indent lines after the first.

My `TSModuleInfo` output:

```
>> default       autopairs  highlight  incremental_selection  indent  
ruby             ✓          ✓          ✗                      ✓       
```

The code:

```ruby
b =
  "b"

a =
  "a" +
  "b"
```

If I highlight this code and press `=`, it becomes:

```ruby
b =
"b"

a =
"a" +
"b"
```

It should turn the latter into the former, not the other way around. Is this a bug, or misconfiguration?

**Comment by maxbrunsfeld** [comment]
Could you open this issue on either Neovim or nvim-treesitter? This repository is just for the ruby parser, but not neovim-specific configuration like indentation.

**Comment by brandoncc** [comment]
Wouldn't it be a parsing error causing it? I looked at the test suite and this type of assignment is not present in the test cases. I'll open it on nvim-treesitter though, thank you for the help :-)

**Comment by maxbrunsfeld** [comment]
Yeah, if you can isolate it as a parsing error (i.e. identify the actual vs expected syntax tree), then it absolutely belongs here.

**Comment by brandoncc** [comment]
I installed the playground and found this:

```ruby
a =
  "a" +
  "b"

a = "a" + "b"
```

```
assignment [0, 0] - [2, 5]
  left: identifier [0, 0] - [0, 1]
  right: binary [1, 2] - [2, 5]
    left: string [1, 2] - [1, 5]
      string_content [1, 3] - [1, 4]
    right: string [2, 2] - [2, 5]
      string_content [2, 3] - [2, 4]
assignment [4, 0] - [4, 13]
  left: identifier [4, 0] - [4, 1]
  right: binary [4, 4] - [4, 13]
    left: string [4, 4] - [4, 7]
      string_content [4, 5] - [4, 6]
    right: string [4, 10] - [4, 13]
      string_content [4, 11] - [4, 12]
```

It looks like the parsing is correct since the trees are the same. Thank you again for the help, I'll open it on nvim-treesitter.
