### ISSUE TITLE
Publish latest version to crates.io and also update its metadata

### ISSUE THREAD

**Issue by jspawar** [tree-sitter/tree-sitter-ruby#183]
So the versions of `tree-sitter`, `tree-sitter-highlight`, and `tree-sitter-ruby` published to crates.io are in a state of dependency hell right now and would be strongly appreciated if we could untangle that please.

Latest version on crates.io or latest git tag of `tree-sitter-ruby` both require `0.17` line of `tree-sitter`; however, if I want to use `tree-sitter-highlight`, there is no `0.17` release line on crates.io. The latest version of `tree-sitter-highlight` (`0.19.2`) tries to use `tree-sitter` `0.19` line which results in dependency collisions when trying to construct a `HighlighterConfiguration`:

```bash
10 | ...on::new(tree_sitter_ruby::language(), tree_sitter_ruby::HIGHLIGHT_QUERY, "", tree_sitter_ruby::LOCALS_QUERY).unwrap();
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `tree_sitter::Language`, found a different struct `tree_sitter::Language`
   |
   = note: perhaps two different versions of crate `tree_sitter` are being used?
```

I see in this repository there is a `v0.19.0` tag; however, its `Cargo.toml` is reporting confusing metadata: https://github.com/tree-sitter/tree-sitter-ruby/blob/v0.19.0/Cargo.toml. For instance, it is still reporting its version as `0.17.0` and still depends on an older version of `tree-sitter`. 

Not sure how y'all would like to resolve this, but I guess an ask would be to at least update the `Cargo.toml` of this repository to report the version in its metadata matching the git tag and update the version of `tree-sitter` it uses (guessing this all would also require shipping a new tag for this repository with those changes).

Straightforward enough to have PR'd; however, dunno how all you are testing all these modules together, so wanted to discuss in case there any caveats with bumping this module's version of `tree-sitter`.

Thanks

**Comment by Ben3eeE** [comment]
Hello, things have been bumped since this issue was opened. Please let us know if you still have any problems :slightly_smiling_face:
