### ISSUE TITLE
Instance variable are highlighted the same as keywords 

### ISSUE THREAD

**Issue by amerov** [tree-sitter/tree-sitter-ruby#184]
![ruby-tree-sitter](https://user-images.githubusercontent.com/196747/126224745-c8f555f1-ab77-4cec-8b68-49b8b1c078e7.png)

**Comment by typoon** [comment]
This is probably an issue with your colorscheme. I just checked and the instance variable has a highlight group of `TSLabel`. Try setting the `TSLabel` highlight to another color in your colorscheme and see if that fixes it for you.

Add this to the end of your $MYVIMRC file and restart nvim:

```
highlight TSKeyword ctermfg=11 guifg='#00ff00'
highlight TSLabel ctermfg=33 guifg='#ff0000'
```

That should make the colors between them different for example purposes.

**Comment by YorickPeterse** [comment]
@amerov @typoon shouldn't instance variables be highlighted as `TSProperty` / `TSField` instead? `TSLabel` isn't meant for fields and such from what I understand, instead it's for labels such as those used for `goto` and such.

**Comment by dgmora** [comment]
Hi! This is still an issue, is there any plan to fix it? Any of `TSProperty`, `TSField` or `TSVariable` would fit better than label.
