### ISSUE TITLE
Interpolation operator not properly highlighted

### ISSUE THREAD

**Issue by typoon** [tree-sitter/tree-sitter-ruby#185]
Hello!

The interpolation operator `#{}` is not being properly highlighted as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/775171/126357117-9c29a4c3-0dc5-44a3-a7b1-1562f0e87117.png)

The screenshots below show the issue where the `}` is not being highlighted as a `TSPunctSpecial` but instead as a `TSPunctBracket`.

Highight for `#`
![Highight for #](https://user-images.githubusercontent.com/775171/126357411-e110f958-152a-4d36-80c5-ff7a483af081.png)

Highlight for `{`
![Highlight for {](https://user-images.githubusercontent.com/775171/126357421-6162a03d-eaea-4a10-8f21-e97a7169fa74.png)

Highlight for `variable`
![Highlight for variable](https://user-images.githubusercontent.com/775171/126357433-513b597a-9bbb-4543-bd49-8744314dc342.png)

Highlight for `}`
![Highlight for }](https://user-images.githubusercontent.com/775171/126357448-9e37ceb8-38cd-4e98-9c81-5467d3bf2714.png)

I tried looking around to see if I could fix this, but I haven't had luck. The parser probably needs to have a way to keep a state in place to know when it is in an interpolation so that it knows to use the `TSPunctSpecial` in the `}` when the is an open `#{`.

**Comment by elebow** [comment]
This appears to be working correctly now. I'm not sure when it was fixed, but it might have been d3066a281d87c71c12dc1233532ba39cb7c5d28d.

<img width="197" alt="Screen Shot 2022-01-26 at 12 36 22" src="https://user-images.githubusercontent.com/7873686/151217331-e3c143fb-10f9-4280-acc4-cdcdafca44cc.png">

<img width="557" alt="Screen Shot 2022-01-26 at 12 36 37" src="https://user-images.githubusercontent.com/7873686/151217338-5897ae4e-0096-4351-aa50-a1cf66928870.png">
