### ISSUE TITLE
Global variables not highlighted

### ISSUE THREAD

**Issue by lmburns** [tree-sitter/tree-sitter-ruby#200]
I see in your code you have a regex for capturing global variables, but could not find it in the `.scm` files. I am unsure how to add global variables to them otherwise I would do that and create a pull request.

When using tree-sitter playground in `nvim`, there is also no capture group name, however when the playground helper is expanded, it does show that it is a `global_variable`, but doesn't have a name such as `rubyTSGlobalVariable`.

I have noticed that they do highlight whenever they're involved in string interpolation, but not when they're by themselves. Picture is related:
![2022-01-16_20-19](https://user-images.githubusercontent.com/44355502/149690564-3a697551-112d-4a26-bd20-bb577bd98bd1.png)

I'll also add that `BEGIN` or `END` are not highlighted either

Extra addition: 
Would it be possible to separate fully capitalized constants from ordinary types?
Another question would be to separate builtin types from custom types?

I'll try and learn how to do some of this to help contribute.

**Comment by yorik1984** [comment]
Fix in https://github.com/nvim-treesitter/nvim-treesitter/commit/8961b598dc68d74e6de4063945e2a4cb159b162c
