### ISSUE TITLE
Heredoc Parse pattern

### ISSUE THREAD

**Issue by Will-Sommers** [tree-sitter/tree-sitter-ruby#204]
Hi y'all — I'm opening an issue here just to ask a question around the parse pattern for Ruby `here_doc`. Specifically, I'm curious about the parse output. Should there be a single wrapper for a here_doc? 

```
a = <<~TEXT
	content
TEXT
```
```
[program] [0, 0] - [4, 0]
  [assignment] [0, 0] - [0, 11]
    left: [identifier] [0, 0] - [0, 1]
    right: [heredoc_beginning] [0, 4] - [0, 11]
  [heredoc_body] [0, 11] - [2, 4]
    [heredoc_content] [0, 11] - [2, 0]
    [heredoc_end] [2, 0] - [2, 4]
```

**Comment by cfroystad** [comment]
I'm not sure it's helpful since there's probably a lot of differences, but this is the second pass at implementing [full Heredoc support in PHP](https://github.com/tree-sitter/tree-sitter-php/pull/121).

Please steal whatever (if anything) may be helpful 🙂

**Comment by maxbrunsfeld** [comment]
It's intentional that they are two separate nodes: in ruby, a heredoc beginning `<<~TEXT` can be separated arbitrarily far from the rest of heredoc.

```ruby
a = foo(<<~TEXT.strip.to_upper).bar().baz() + "some other string" # and a comment
   finally the content appears, after a lot of other syntax
TEXT

```
