### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by vfonic** [tree-sitter/tree-sitter-ruby#219]
Hi!

I just found tree-sitter-ruby through endwise/endsitter VS Code extension:
https://github.com/kaiwood/vscode-endwise/pull/32

Endsitter works great, except that it doesn't support Ruby 3.0 and 3.1 syntax. I'm using Ruby 3.1 in most of my projects so this would really help me use Endsitter extension to the max. :)

I see tree-sitter-ruby has added support for Ruby 3.1, but the last release of this package on npm has been about a year ago. Any chance to get new version published?

Thank you! 🙏

**Comment by Ben3eeE** [comment]
Seems like this went between the cracks and that new versions have already been released since this was opened. Thanks for reaching out :+1:

**Comment by vfonic** [comment]
Hey @Ben3eeE!

Where can I find new version of tree-sitter-ruby npm package?

I see here on the npmjs.com that the last version that was released was 2 years ago:
https://www.npmjs.com/package/tree-sitter-ruby

Thanks!

**Comment by Ben3eeE** [comment]
Hey, It seems that the latest version is not tagged and released: https://github.com/tree-sitter/tree-sitter-ruby/issues/232

I'm checking how to get this moving :)
