### ISSUE TITLE
Ruby parser.c size

### ISSUE THREAD

**Issue by bkramer-relyance** [tree-sitter/tree-sitter-ruby#223]
The Ruby parser seems to generally work well, and if it takes an oversized parse table to drive it, then okay.  However, doing `git clone` of the Tree sitter repo, especially on CI/CD environments, seems to take an unfair amount of time.  One way this could be mitigated by compressing `parser.c`. Any thoughts?

**Comment by dcreager** [comment]
This has come up before not just for the Ruby grammar; please see https://github.com/tree-sitter/tree-sitter/discussions/1243 for additional discussion. The current plan is to stop checking in the generated files as part of a 1.0 release of tree-sitter.

**Comment by Ben3eeE** [comment]
Closing in favor of https://github.com/tree-sitter/tree-sitter/issues/930
