### ISSUE TITLE
0.20.0 is not tagged

### ISSUE THREAD

**Issue by ojab** [tree-sitter/tree-sitter-ruby#232]
Since 0.19.0 was released on `0.19.0` commit, I suppose that version-bump should happen on release time. There is 0.20.0 commit in the repo https://github.com/tree-sitter/tree-sitter-ruby/commit/c91960320d0f337bdd48308a8ad5500bd2616979, but no tag/release.

**Comment by Ben3eeE** [comment]
@maxbrunsfeld how do releases work here? Can I just tag 0.20.0 from the commit and push it? Or is there something else to take into account?

**Comment by jirutka** [comment]
> Can I just tag 0.20.0 from the commit and push it?

Yes. Can you please do it?

**Comment by akimd** [comment]
Please, tag this release.  We have whole CIs jammed because of this.

Thanks in advance!
