### ISSUE TITLE
Add support for *.html.slim filetypes

### ISSUE THREAD

**Issue by apilot** [tree-sitter/tree-sitter-ruby#243]
Tree-sitter supported by multiple editors, and enabling support for this format will empower these editors
[Slim-template](https://slim-template.github.io/)

**Comment by amaanq** [comment]
The solution would be to create a grammar called "slim" that extends off the Ruby one to support these filetypes, not change the Ruby one itself

**Comment by apilot** [comment]
what is the best way to do this to include support? just in ruby itself there is already support for html.erb if I do not confuse anything. and it's the same in a different format.
