### ISSUE TITLE
Error `fatal error: 'cstring' file not found` when compiling in MacBook M2

### ISSUE THREAD

**Issue by enrique-fernandez-polo** [tree-sitter/tree-sitter-ruby#248]
Hello there!

I am struggling to get this working in my laptop 

```
nvim-treesitter[ruby]: Error during compilation
src/scanner.cc:4:10: fatal error: 'cstring' file not found
#include <cstring>
         ^~~~~~~~~
1 error generated.
```

I 've been playing around with `gcc`, `llvm` but I do not have that kind of knowledge 😅

Could you give me hand?? Thanks!

**Comment by enrique-fernandez-polo** [comment]
Well you know... You just have to create a issue to find the solution.

I had to set the `CC` env var to the proper path of the `gcc` command installed by brew.

`CC=/opt/homebrew/bin/gcc-13 lvim .` Did the trick.

**Comment by amaanq** [comment]
the grammar was just updated to have the scanner be written in C fyi to prevent issues like this in the future.
