### ISSUE TITLE
%w/%W/%i/%I children should be strings/symbols

### ISSUE THREAD

**Issue by robrix** [tree-sitter/tree-sitter-ruby#6]
Ruby’s `%w`/`%W`, and `%i`/`%I` syntaxes are array literals containing strings and symbols respectively. However, the parse tree won’t contain nodes with the appropriate names, even with the changes described in https://github.com/tree-sitter/tree-sitter/pull/29.

I would like this source:

``` ruby
%w(hello world)
```

to end up with this parse tree:

```
(program (expression.literal.array (expression.literal.string) (expression.literal.string)))
```

However, note that the elements of the array would not be parsed via the `string` production; they’d be parsed via the `array` and named `string` sort of by fiat.

@maxbrunsfeld: Is there any way to assign names like that? API like this might do it:

``` js
rules: {
  array: choice(
    seq('[', commaSep($.expression), ']'),
    seq('%w(', sep({ string: /[^\s]+/ }, /\s+/), ')'),
    …
  ),
  …
}
```

Motivated by #4.

**Comment by maxbrunsfeld** [comment]
I think that having some way of naming pieces of a rule would be cool. I think in the meantime though, you could just do:

```js
array: $ => choice(
  // ...
  seq('%w(', sep($.bare_string, /\s+/), ')')
),

bare_string: $ => (/[^\s]+/),
```

So that you get this parse tree:

```
(program (expression.literal.array (bare_string) (bare_string)))
```

That way, at least you get a node for each string in the array. They're semantically strings, but syntactically a different construct, so I think it is reasonable for them to appear differently in the parse tree.

**Comment by maxbrunsfeld** [comment]
I was just testing with `ripper`, to see how ruby's own parser treats this.

```ruby
> Ripper.sexp "['one']"
=> [:program, [[:array, [[:string_literal, [:string_content, [:@tstring_content, "one", [1, 2]]]]]]]]

> Ripper.sexp "%w(one)"
=> [:program, [[:array, [[:@tstring_content, "one", [1, 3]]]]]]
```

**Comment by robrix** [comment]
Oh, interesting find—thanks for looking into that!
