### ISSUE TITLE
Infinite loop when scanning symbol identifiers

### ISSUE THREAD

**Issue by philipturnbull** [tree-sitter/tree-sitter-ruby#83]
An infinite loop can be triggered in the scanner when an input ends with a symbol, e.g.

```bash
$ echo -n ':foo' >/tmp/symbol
$ hexdump -C /tmp/symbol
00000000  3a 66 6f 6f                                       |:foo|
00000004
$ /node_modules/.bin/tree-sitter parse /tmp/symbol
^C
```

I believe this caused by this loop:

https://github.com/tree-sitter/tree-sitter-ruby/blob/7a1ecb7d145e8e91a86f47c6c4ed0dba98532a7a/src/scanner.cc#L357-L359

When we reach the end of the buffer, `->lookahead` is zero so is not an identifier character and `advance(...)` is a no-op so we never make any forward progress.

**Comment by maxbrunsfeld** [comment]
Oh, yeah `is_iden_char` should return false for the zero character. We should add zero to the `NON_IDENTIFIER_CHARS` array.
