### ISSUE TITLE
Incorrect parsing of a method given a hash without brackets inside of a block

### ISSUE THREAD

**Issue by justinlocsei** [tree-sitter/tree-sitter-ruby#95]
First of all, thank you for this amazing project, which has made something I'm working on much easier to implement!  In the process of using tree-sitter, I noticed that it produces an unexpected result for the following syntax:

```ruby
format.json { render :key => value }
```

This produced the following syntax tree:

```
(program (method_call (call (identifier) (identifier)) (argument_list (hash (pair (method_call (identifier) (argument_list (symbol))) (identifier))))))
```

However, the expected result was:

```
(program (method_call (call (identifier) (identifier)) (block (method_call (identifier) (argument_list (pair (symbol) (identifier)))))))
```

Basically, it looks like tree-sitter is treating the contents of the curlies as a method call that's receiving a hash whose key is itself a method call, instead of a method call with an implicit hash as its only argument.  For reference, the expected output is produced from any of the following forms:

```ruby
format.json { render(:key => value) }
format.json { render {:key => value} }
format.json { render key: value }
```

Given that, it seems like the unexpected behavior is only triggered when using hash rockets.  I tried parsing the code that produced the unexpected tree using whitequark's Ruby parser, and it correctly produced the block form.  

Thanks again for this project, and sorry for being the bearer of bug news.  If you need any more information, just let me know!

**Comment by maxbrunsfeld** [comment]
I believe this is fixed on master. Thank you for the detailed bug report!

**Comment by justinlocsei** [comment]
Awesome!  Thank you very much for fixing this!
