### ISSUE TITLE
Distinguish protected and private methods and constants

### ISSUE THREAD

**Issue by rewinfrey** [tree-sitter/tree-sitter-ruby#98]
Given the following Ruby code:

```ruby
class Example
  def bar; end

  private
  def foo; end
end
```

Today `tree-sitter-ruby` produces:

```shell
(program [0, 0] - [6, 0]
  (class [0, 0] - [5, 3]
    (constant [0, 6] - [0, 13])
    (method [1, 2] - [1, 14]
      (identifier [1, 6] - [1, 9]))
    (identifier [3, 2] - [3, 9])
    (method [4, 2] - [4, 14]
      (identifier [4, 6] - [4, 9]))))
```

@maxbrunsfeld what do you think about changing the parse tree to communicate private or protected members? It'd be great from a client perspective if the parse tree could reflect the visibility of a member e.g. `private_method` or `protected_constant` (with the default always indicating public visibility). One advantage is that clients wouldn't require state to track what visibility scope (nor have to make a check against each `identifier`) in the parse tree for `protected` or `private`, but I'm guessing this would require an additional piece of state on the external scanner and would further complicate the grammar. What do you think?

**Comment by maxbrunsfeld** [comment]
Yeah, I just recently was surprised to learn that:
1. We weren't parsing `private` and friends as keywords
2. We were *correct* to not parse them as keywords

I think that technically, part of evaluating ruby correctly would be evaluating those methods like `private`, `public`, `protected`.

**Comment by rewinfrey** [comment]
Thank you @maxbrunsfeld and @patrickt for explaining Ruby's use of _methods_ rather than _keywords_ for visibility. I'm going to close this out as I don't think there's any action to take within `tree-sitter-ruby` now.
