### ISSUE TITLE
require_relative should be 'syntax--support' same as require

### ISSUE THREAD

**Issue by chenjau** [tree-sitter/tree-sitter-ruby#99]
<img width="264" alt="shot" src="https://user-images.githubusercontent.com/7047842/50474782-41649f00-09fd-11e9-9253-46773ddd5550.png">

require_relative has class: 'syntax--entity syntax--name syntax--function'.
require          has class: 'syntax--support syntax--function'.

I think both of them should be belongs to 'syntax--support', right?

**Comment by Ben3eeE** [comment]
Thanks for contributing 🙇 

This is an issue with `atom/language-ruby` and not tree-sitter-ruby. It seems that there is already an issue opened for this https://github.com/atom/language-ruby/issues/246. You may want to subscribe there for updates.
